# Generated by Django 5.1.3 on 2024-11-21 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_smart', '0002_alter_customuser_options_customuser_ciudad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_seguimiento', models.CharField(editable=False, max_length=15, unique=True, verbose_name='Número de seguimiento')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del pedido')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de envío'), ('PREPARACION', 'En preparación'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado del pedido')),
                ('direccion_envio', models.TextField(verbose_name='Dirección de envío')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total del pedido')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualización')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de envío'), ('PREPARACION', 'En preparación'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], max_length=20, verbose_name='Estado')),
                ('descripcion', models.TextField(verbose_name='Descripción del estado')),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='stock_smart.pedido')),
            ],
            options={
                'verbose_name': 'Seguimiento de pedido',
                'verbose_name_plural': 'Seguimientos de pedidos',
                'ordering': ['-fecha'],
            },
        ),
    ]
