# Generated by Django 5.1.3 on 2024-11-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_smart', '0004_alter_categoria_padre_alter_categoria_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productos_por_fila', models.IntegerField(default=4, help_text='Número de productos por fila')),
                ('productos_destacados_visible', models.BooleanField(default=True)),
                ('productos_vendidos_visible', models.BooleanField(default=True)),
                ('productos_nuevos_visible', models.BooleanField(default=True)),
                ('max_productos_por_seccion', models.IntegerField(default=8, help_text='Máximo de productos por sección')),
            ],
            options={
                'verbose_name': 'Configuración del Home',
                'verbose_name_plural': 'Configuraciones del Home',
            },
        ),
    ]
