# Generated by Django 5.1.3 on 2024-11-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_smart', '0004_alter_category_options_category_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Porcentaje de descuento'),
        ),
        migrations.AddField(
            model_name='producto',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Destacado'),
        ),
    ]
