# Generated by Django 5.1.3 on 2024-11-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_smart', '0005_configuracionhome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionhome',
            name='max_productos_por_seccion',
        ),
        migrations.RemoveField(
            model_name='configuracionhome',
            name='productos_por_fila',
        ),
        migrations.AddField(
            model_name='configuracionhome',
            name='productos_por_columna',
            field=models.IntegerField(default=5, help_text='Número de productos por columna'),
        ),
        migrations.AlterField(
            model_name='configuracionhome',
            name='productos_destacados_visible',
            field=models.BooleanField(default=True, verbose_name='Mostrar Productos Destacados'),
        ),
        migrations.AlterField(
            model_name='configuracionhome',
            name='productos_nuevos_visible',
            field=models.BooleanField(default=True, verbose_name='Mostrar Productos Nuevos'),
        ),
        migrations.AlterField(
            model_name='configuracionhome',
            name='productos_vendidos_visible',
            field=models.BooleanField(default=True, verbose_name='Mostrar Productos Más Vendidos'),
        ),
    ]
